//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association_Managment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobMember
    {
        public long Code { get; set; }
        public long CodeMember { get; set; }
        public long CodeJob { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> DeleteRow { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Member Member { get; set; }
    }
}
