//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association_Managment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeMeeting
    {
        public long CodeType { get; set; }
        public string NameType { get; set; }
        public Nullable<int> NumOfMembers { get; set; }
    }
}
